normalization_enabled = true
bitcoin_rpc_proxy_enabled = false
grpc_server_enabled = true
hooks_enabled = true
webhooks = []
control_port = 20446
ingestion_port = 20445
bitcoind_rpc_username = "devnet"
bitcoind_rpc_password = "devnet"
bitcoind_rpc_host = "localhost"
bitcoind_rpc_port = 18443
stacks_node_rpc_host = "localhost"
stacks_node_rpc_port = 20443
operators = ["74738ff5-5367-5958-9aee-98fffdcd1876"]